PROGRAM LOOP3D
   ! Description:
   ! This is a simplified version of the original LOOP3D mini-app that only calculates
   ! the x-component of the velocity flux. The method uses C-bindings for fine-grained control
   ! over device allocations and host-device data movement. Additionally, the arrays of 
   ! derived data types from the original code, CELL and EDGE, have been unpacked
   ! into plain arrays following an array-of-structures (AoS) format.
   USE OMP_LIB
   USE ISO_C_BINDING
   IMPLICIT NONE
   
   ! Miscellaneous declarations
   INTEGER :: ISTEP
   INTEGER, PARAMETER :: NUM_TIME_STEPS = 100
   INTEGER, PARAMETER :: IBAR = 256, JBAR = 256, KBAR = 256
   INTEGER, PARAMETER :: NEDGE = 12
   INTEGER, PARAMETER :: IBP1 = IBAR+1, JBP1 = JBAR+1, KBP1 = KBAR+1
   INTEGER, PARAMETER :: IBP2 = IBP1+1, JBP2 = JBP1+1, KBP2 = KBP1+1
   INTEGER, PARAMETER :: EB = SELECTED_REAL_KIND(12)
   REAL(EB), PARAMETER :: FOTH = 4.0_EB/3.0_EB
   REAL(EB) :: FVX_AVG, FVY_AVG, FVZ_AVG
   
   ! Host C-pointer declarations
   TYPE(C_PTR) :: X_HOST_CPTR, Y_HOST_CPTR, Z_HOST_CPTR
   TYPE(C_PTR) :: RDXN_HOST_CPTR, RDYN_HOST_CPTR, RDZN_HOST_CPTR, RDX_HOST_CPTR, RDY_HOST_CPTR, RDZ_HOST_CPTR
   TYPE(C_PTR) :: CELL_INDEX_HOST_CPTR, CELL_HOST_CPTR
   TYPE(C_PTR) :: OMEGA_HOST_CPTR, TAU_HOST_CPTR
   TYPE(C_PTR) :: RHO_HOST_CPTR, RHO_0_HOST_CPTR
   TYPE(C_PTR) :: D_HOST_CPTR, MU_HOST_CPTR
   TYPE(C_PTR) :: WORK1_HOST_CPTR, WORK2_HOST_CPTR, WORK3_HOST_CPTR, WORK4_HOST_CPTR, WORK5_HOST_CPTR, WORK6_HOST_CPTR
   TYPE(C_PTR) :: GX_HOST_CPTR, GY_HOST_CPTR, GZ_HOST_CPTR
   TYPE(C_PTR) :: U_HOST_CPTR, V_HOST_CPTR, W_HOST_CPTR
   TYPE(C_PTR) :: UU_HOST_CPTR, VV_HOST_CPTR, WW_HOST_CPTR
   TYPE(C_PTR) :: DP_HOST_CPTR, RHOP_HOST_CPTR
   TYPE(C_PTR) :: TXY_HOST_CPTR, TXZ_HOST_CPTR, TYZ_HOST_CPTR
   TYPE(C_PTR) :: OMX_HOST_CPTR, OMY_HOST_CPTR, OMZ_HOST_CPTR
   TYPE(C_PTR) :: FVX_HOST_CPTR, FVY_HOST_CPTR, FVZ_HOST_CPTR

   ! Device C-pointer declarations
   TYPE(C_PTR) :: RDXN_DEVICE_CPTR, RDYN_DEVICE_CPTR, RDZN_DEVICE_CPTR, RDX_DEVICE_CPTR, RDY_DEVICE_CPTR, RDZ_DEVICE_CPTR
   TYPE(C_PTR) :: CELL_INDEX_DEVICE_CPTR, CELL_DEVICE_CPTR
   TYPE(C_PTR) :: OMEGA_DEVICE_CPTR, TAU_DEVICE_CPTR
   TYPE(C_PTR) :: RHO_DEVICE_CPTR, RHO_0_DEVICE_CPTR
   TYPE(C_PTR) :: D_DEVICE_CPTR, MU_DEVICE_CPTR
   TYPE(C_PTR) :: WORK1_DEVICE_CPTR, WORK2_DEVICE_CPTR, WORK3_DEVICE_CPTR, WORK4_DEVICE_CPTR, WORK5_DEVICE_CPTR, WORK6_DEVICE_CPTR
   TYPE(C_PTR) :: GX_DEVICE_CPTR, GY_DEVICE_CPTR, GZ_DEVICE_CPTR
   TYPE(C_PTR) :: U_DEVICE_CPTR, V_DEVICE_CPTR, W_DEVICE_CPTR
   TYPE(C_PTR) :: UU_DEVICE_CPTR, VV_DEVICE_CPTR, WW_DEVICE_CPTR
   TYPE(C_PTR) :: DP_DEVICE_CPTR, RHOP_DEVICE_CPTR
   TYPE(C_PTR) :: TXY_DEVICE_CPTR, TXZ_DEVICE_CPTR, TYZ_DEVICE_CPTR
   TYPE(C_PTR) :: OMX_DEVICE_CPTR, OMY_DEVICE_CPTR, OMZ_DEVICE_CPTR
   TYPE(C_PTR) :: FVX_DEVICE_CPTR, FVY_DEVICE_CPTR, FVZ_DEVICE_CPTR

   ! Host Fortran pointer declarations
   REAL(KIND=C_DOUBLE), POINTER :: X_HOST_FPTR (:)
   REAL(KIND=C_DOUBLE), POINTER :: Y_HOST_FPTR (:)
   REAL(KIND=C_DOUBLE), POINTER :: Z_HOST_FPTR (:)
   REAL(KIND=C_DOUBLE), POINTER, DIMENSION(:) :: RDXN_HOST_FPTR, RDYN_HOST_FPTR, RDZN_HOST_FPTR
   REAL(KIND=C_DOUBLE), POINTER, DIMENSION(:) :: RDX_HOST_FPTR, RDY_HOST_FPTR, RDZ_HOST_FPTR
   INTEGER(C_INT), POINTER, DIMENSION(:) :: CELL_INDEX_HOST_FPTR, CELL_HOST_FPTR
   REAL(KIND=C_DOUBLE), POINTER, DIMENSION(:) :: OMEGA_HOST_FPTR, TAU_HOST_FPTR
   REAL(KIND=C_DOUBLE), POINTER, DIMENSION(:) :: RHO_HOST_FPTR, RHO_0_HOST_FPTR, D_HOST_FPTR, MU_HOST_FPTR
   REAL(KIND=C_DOUBLE), POINTER, DIMENSION(:) :: WORK1_HOST_FPTR, WORK2_HOST_FPTR, WORK3_HOST_FPTR, WORK4_HOST_FPTR, WORK5_HOST_FPTR, WORK6_HOST_FPTR
   REAL(KIND=C_DOUBLE), POINTER, DIMENSION(:) :: GX_HOST_FPTR, GY_HOST_FPTR, GZ_HOST_FPTR
   REAL(KIND=C_DOUBLE), POINTER, DIMENSION(:) :: U_HOST_FPTR, V_HOST_FPTR, W_HOST_FPTR
   REAL(KIND=C_DOUBLE), POINTER, DIMENSION(:) :: UU_HOST_FPTR, VV_HOST_FPTR, WW_HOST_FPTR
   REAL(KIND=C_DOUBLE), POINTER, DIMENSION(:) :: DP_HOST_FPTR, RHOP_HOST_FPTR
   REAL(KIND=C_DOUBLE), POINTER, DIMENSION(:) :: TXY_HOST_FPTR, TXZ_HOST_FPTR, TYZ_HOST_FPTR
   REAL(KIND=C_DOUBLE), POINTER, DIMENSION(:) :: OMX_HOST_FPTR, OMY_HOST_FPTR, OMZ_HOST_FPTR
   REAL(KIND=C_DOUBLE), POINTER, DIMENSION(:) :: FVX_HOST_FPTR

   ! Device Fortran pointer declarations
   REAL(KIND=C_DOUBLE), POINTER, DIMENSION(:) :: RDXN_DEVICE_FPTR, RDYN_DEVICE_FPTR, RDZN_DEVICE_FPTR
   REAL(KIND=C_DOUBLE), POINTER, DIMENSION(:) :: RDX_DEVICE_FPTR, RDY_DEVICE_FPTR, RDZ_DEVICE_FPTR
   INTEGER(C_INT), POINTER, DIMENSION(:) :: CELL_INDEX_DEVICE_FPTR, CELL_DEVICE_FPTR
   REAL(KIND=C_DOUBLE), POINTER, DIMENSION(:) :: OMEGA_DEVICE_FPTR, TAU_DEVICE_FPTR
   REAL(KIND=C_DOUBLE), POINTER, DIMENSION(:) :: RHO_0_DEVICE_FPTR, MU_DEVICE_FPTR
   REAL(KIND=C_DOUBLE), POINTER, DIMENSION(:) :: GX_DEVICE_FPTR, GY_DEVICE_FPTR, GZ_DEVICE_FPTR
   REAL(KIND=C_DOUBLE), POINTER, DIMENSION(:) :: UU_DEVICE_FPTR, VV_DEVICE_FPTR, WW_DEVICE_FPTR
   REAL(KIND=C_DOUBLE), POINTER, DIMENSION(:) :: DP_DEVICE_FPTR, RHOP_DEVICE_FPTR
   REAL(KIND=C_DOUBLE), POINTER, DIMENSION(:) :: TXY_DEVICE_FPTR, TXZ_DEVICE_FPTR, TYZ_DEVICE_FPTR
   REAL(KIND=C_DOUBLE), POINTER, DIMENSION(:) :: OMX_DEVICE_FPTR, OMY_DEVICE_FPTR, OMZ_DEVICE_FPTR
   REAL(KIND=C_DOUBLE), POINTER, DIMENSION(:) :: FVX_DEVICE_FPTR, FVY_DEVICE_FPTR, FVZ_DEVICE_FPTR

   ! Misc. declarations
   REAL(EB) :: MUX,MUY,MUZ,UP,UM,VP,VM,WP,WM,VTRM,OMXP,OMXM,OMYP,OMYM,OMZP,OMZM,TXYP,TXYM,TXZP,TXZM,TYZP,TYZM, &
               DTXYDY,DTXZDZ,DTYZDZ,DTXYDX,DTXZDX,DTYZDY, &
               DUDX,DVDY,DWDZ,DUDY,DUDZ,DVDX,DVDZ,DWDX,DWDY, &
               VOMZ,WOMY,UOMY,VOMX,UOMZ,WOMX, &
               RRHO,TXXP,TXXM,TYYP,TYYM,TZZP,TZZM,DTXXDX,DTYYDY,DTZZDZ
   REAL(EB) :: T_NOW,T_END
   INTEGER :: I,J,K,IEXP,IEXM,IEYP,IEYM,IEZP,IEZM,IC,ICMAX,IC1,IC2,IE,MAX_EDGE,MAX_EDGE_P1,NT
   CHARACTER(LEN=50) :: FILENAME
   INTEGER(C_INT) :: HOST_DEV, TARG_DEV, RC
   INTEGER(C_SIZE_T) :: REAL_BYTES, INT_BYTES
   
   ! Write out Starting:
   !$OMP PARALLEL
   !$OMP MASTER
   !$ NT = OMP_GET_NUM_THREADS()
   !$OMP END MASTER
   !$OMP BARRIER
   !$OMP END PARALLEL

   HOST_DEV  = OMP_GET_INITIAL_DEVICE()
   TARG_DEV = OMP_GET_DEFAULT_DEVICE()
   REAL_BYTES = C_SIZEOF(T_NOW)
   INT_BYTES = C_SIZEOF(ISTEP)
   
   WRITE(FILENAME,'(A,I3,A,I3,A,I3,A)') 'loop3d_',IBAR,'GRID_',NT,'THR_',NUM_TIME_STEPS,'STEPS_GPU_V0.txt'
   WRITE(*,*) 'Starting Loop3D, out file: ',TRIM(FILENAME)
   OPEN(UNIT=10,FILE=TRIM(FILENAME),STATUS='UNKNOWN')
   WRITE(10,*) 'Number of devices=',OMP_GET_NUM_DEVICES()
   WRITE(10,*) 'Starting Loop3D'
   WRITE(10,*) 'IBAR=',IBAR,' JBAR=',JBAR,' KBAR=',KBAR,' OMP_NUM_THREADS=',NT
   
   ! Host-allocations:
   X_HOST_CPTR = OMP_TARGET_ALLOC(IBP1*REAL_BYTES,HOST_DEV)
   Y_HOST_CPTR = OMP_TARGET_ALLOC(JBP1*REAL_BYTES,HOST_DEV)
   Z_HOST_CPTR = OMP_TARGET_ALLOC(KBP1*REAL_BYTES,HOST_DEV)
   RDXN_HOST_CPTR = OMP_TARGET_ALLOC(IBP1*REAL_BYTES,HOST_DEV)
   RDYN_HOST_CPTR = OMP_TARGET_ALLOC(JBP1*REAL_BYTES,HOST_DEV)
   RDZN_HOST_CPTR = OMP_TARGET_ALLOC(KBP1*REAL_BYTES,HOST_DEV)
   RDX_HOST_CPTR = OMP_TARGET_ALLOC(IBP1*REAL_BYTES,HOST_DEV)
   RDY_HOST_CPTR = OMP_TARGET_ALLOC(JBP1*REAL_BYTES,HOST_DEV)
   RDZ_HOST_CPTR = OMP_TARGET_ALLOC(KBP1*REAL_BYTES,HOST_DEV)
   CELL_INDEX_HOST_CPTR = OMP_TARGET_ALLOC(IBP2*JBP2*KBP2*INT_BYTES,HOST_DEV)
   RHO_HOST_CPTR = OMP_TARGET_ALLOC(IBP2*JBP2*KBP2*REAL_BYTES,HOST_DEV)
   D_HOST_CPTR = OMP_TARGET_ALLOC(IBP2*JBP2*KBP2*REAL_BYTES,HOST_DEV)
   MU_HOST_CPTR = OMP_TARGET_ALLOC(IBP2*JBP2*KBP2*REAL_BYTES,HOST_DEV)
   WORK1_HOST_CPTR = OMP_TARGET_ALLOC(IBP2*JBP2*KBP2*REAL_BYTES,HOST_DEV)
   WORK2_HOST_CPTR = OMP_TARGET_ALLOC(IBP2*JBP2*KBP2*REAL_BYTES,HOST_DEV)
   WORK3_HOST_CPTR = OMP_TARGET_ALLOC(IBP2*JBP2*KBP2*REAL_BYTES,HOST_DEV)
   WORK4_HOST_CPTR = OMP_TARGET_ALLOC(IBP2*JBP2*KBP2*REAL_BYTES,HOST_DEV)
   WORK5_HOST_CPTR = OMP_TARGET_ALLOC(IBP2*JBP2*KBP2*REAL_BYTES,HOST_DEV)
   WORK6_HOST_CPTR = OMP_TARGET_ALLOC(IBP2*JBP2*KBP2*REAL_BYTES,HOST_DEV)
   RHO_0_HOST_CPTR = OMP_TARGET_ALLOC(KBP1*REAL_BYTES,HOST_DEV)
   GX_HOST_CPTR = OMP_TARGET_ALLOC(IBP1*REAL_BYTES,HOST_DEV)
   GY_HOST_CPTR = OMP_TARGET_ALLOC(IBP1*REAL_BYTES,HOST_DEV)
   GZ_HOST_CPTR = OMP_TARGET_ALLOC(IBP1*REAL_BYTES,HOST_DEV)
   U_HOST_CPTR = OMP_TARGET_ALLOC(IBP2*JBP2*KBP2*REAL_BYTES,HOST_DEV)
   V_HOST_CPTR = OMP_TARGET_ALLOC(IBP2*JBP2*KBP2*REAL_BYTES,HOST_DEV)
   W_HOST_CPTR = OMP_TARGET_ALLOC(IBP2*JBP2*KBP2*REAL_BYTES,HOST_DEV)
   FVX_HOST_CPTR = OMP_TARGET_ALLOC(IBP2*JBP2*KBP2*REAL_BYTES,HOST_DEV)
   ! Device-allocations:
   RDXN_DEVICE_CPTR = OMP_TARGET_ALLOC(IBP1*REAL_BYTES,TARG_DEV)
   RDYN_DEVICE_CPTR = OMP_TARGET_ALLOC(JBP1*REAL_BYTES,TARG_DEV)
   RDZN_DEVICE_CPTR = OMP_TARGET_ALLOC(KBP1*REAL_BYTES,TARG_DEV)
   RDX_DEVICE_CPTR = OMP_TARGET_ALLOC(IBP1*REAL_BYTES,TARG_DEV)
   RDY_DEVICE_CPTR = OMP_TARGET_ALLOC(JBP1*REAL_BYTES,TARG_DEV)
   RDZ_DEVICE_CPTR = OMP_TARGET_ALLOC(KBP1*REAL_BYTES,TARG_DEV)
   CELL_INDEX_DEVICE_CPTR = OMP_TARGET_ALLOC(IBP2*JBP2*KBP2*INT_BYTES,TARG_DEV)
   RHO_DEVICE_CPTR = OMP_TARGET_ALLOC(IBP2*JBP2*KBP2*REAL_BYTES,TARG_DEV)
   D_DEVICE_CPTR = OMP_TARGET_ALLOC(IBP2*JBP2*KBP2*REAL_BYTES,TARG_DEV)
   MU_DEVICE_CPTR = OMP_TARGET_ALLOC(IBP2*JBP2*KBP2*REAL_BYTES,TARG_DEV)
   WORK1_DEVICE_CPTR = OMP_TARGET_ALLOC(IBP2*JBP2*KBP2*REAL_BYTES,TARG_DEV)
   WORK2_DEVICE_CPTR = OMP_TARGET_ALLOC(IBP2*JBP2*KBP2*REAL_BYTES,TARG_DEV)
   WORK3_DEVICE_CPTR = OMP_TARGET_ALLOC(IBP2*JBP2*KBP2*REAL_BYTES,TARG_DEV)
   WORK4_DEVICE_CPTR = OMP_TARGET_ALLOC(IBP2*JBP2*KBP2*REAL_BYTES,TARG_DEV)
   WORK5_DEVICE_CPTR = OMP_TARGET_ALLOC(IBP2*JBP2*KBP2*REAL_BYTES,TARG_DEV)
   WORK6_DEVICE_CPTR = OMP_TARGET_ALLOC(IBP2*JBP2*KBP2*REAL_BYTES,TARG_DEV)
   RHO_0_DEVICE_CPTR = OMP_TARGET_ALLOC(KBP1*REAL_BYTES,TARG_DEV)
   GX_DEVICE_CPTR = OMP_TARGET_ALLOC(IBP1*REAL_BYTES,TARG_DEV)
   GY_DEVICE_CPTR = OMP_TARGET_ALLOC(IBP1*REAL_BYTES,TARG_DEV)
   GZ_DEVICE_CPTR = OMP_TARGET_ALLOC(IBP1*REAL_BYTES,TARG_DEV)
   U_DEVICE_CPTR = OMP_TARGET_ALLOC(IBP2*JBP2*KBP2*REAL_BYTES,TARG_DEV)
   V_DEVICE_CPTR = OMP_TARGET_ALLOC(IBP2*JBP2*KBP2*REAL_BYTES,TARG_DEV)
   W_DEVICE_CPTR = OMP_TARGET_ALLOC(IBP2*JBP2*KBP2*REAL_BYTES,TARG_DEV)
   FVX_DEVICE_CPTR = OMP_TARGET_ALLOC(IBP2*JBP2*KBP2*REAL_BYTES,TARG_DEV)

   ! Initialize on the host:
   CALL C_F_POINTER(X_HOST_CPTR,X_HOST_FPTR,shape=[ IBP1 ])
   CALL C_F_POINTER(RDXN_HOST_CPTR,RDXN_HOST_FPTR,shape=[ IBP1 ])
   CALL C_F_POINTER(RDX_HOST_CPTR,RDX_HOST_FPTR,shape=[ IBP1 ])
   DO I=0,IBAR
      X_HOST_FPTR(I)    = REAL(I,EB)
      RDXN_HOST_FPTR(I) = 1.0_EB
      RDX_HOST_FPTR(I)  = 1.0_EB
   ENDDO
   CALL C_F_POINTER(Y_HOST_CPTR,Y_HOST_FPTR,shape=[ JBP1 ])
   CALL C_F_POINTER(RDYN_HOST_CPTR,RDYN_HOST_FPTR,shape=[ JBP1 ])
   CALL C_F_POINTER(RDY_HOST_CPTR,RDY_HOST_FPTR,shape=[ JBP1 ])
   DO J=0,JBAR
      Y_HOST_FPTR(J)    = REAL(J,EB)
      RDYN_HOST_FPTR(J) = 1.0_EB
      RDY_HOST_FPTR(J)  = 1.0_EB
   ENDDO
   CALL C_F_POINTER(Z_HOST_CPTR,Z_HOST_FPTR,shape=[ KBP1 ])
   CALL C_F_POINTER(RDZN_HOST_CPTR,RDZN_HOST_FPTR,shape=[ KBP1 ])
   CALL C_F_POINTER(RDZ_HOST_CPTR,RDZ_HOST_FPTR,shape=[ KBP1 ])
   DO K=0,KBAR
      Z_HOST_FPTR(K)    = REAL(K,EB)
      RDZN_HOST_FPTR(K) = 1.0_EB
      RDZ_HOST_FPTR(K)  = 1.0_EB
   ENDDO

   ! Cell Index, Cell and Edge quantities
   CALL C_F_POINTER(CELL_INDEX_HOST_CPTR,CELL_INDEX_HOST_FPTR,shape=[ IBP2*JBP2*KBP2 ])
   CELL_INDEX_HOST_FPTR(:) = 0
   IC = 0
   DO K=1,KBAR
      DO J=1,JBAR
         DO I=1,IBAR
            IF( .NOT. (ANY( K==(/1,KBAR/) ) .OR. ANY( J==(/1,JBAR/) ) .OR. ANY( I==(/1,IBAR/) )) ) CYCLE
            IC = IC + 1
            CELL_INDEX_HOST_FPTR(LINEAR_IDX(I,J,K,IBP2,JBP2,KBP2)) = IC
         ENDDO
      ENDDO
   ENDDO
   ICMAX = IC + 1
   CELL_HOST_CPTR = OMP_TARGET_ALLOC((NEDGE*ICMAX+1)*INT_BYTES,HOST_DEV)
   CELL_DEVICE_CPTR = OMP_TARGET_ALLOC((NEDGE*ICMAX+1)*INT_BYTES,TARG_DEV)
   CALL C_F_POINTER(CELL_HOST_CPTR,CELL_HOST_FPTR,shape=[ NEDGE*ICMAX+1 ])
   IC = 0
   MAX_EDGE=-1
   DO K=1,KBAR
      DO J=1,JBAR
         DO I=1,IBAR
            IF( .NOT. (ANY( K==(/1,KBAR/) ) .OR. ANY( J==(/1,JBAR/) ) .OR. ANY( I==(/1,IBAR/) )) ) CYCLE
            IC = IC + 1
            CELL_HOST_FPTR(IC * NEDGE + 1)  = CELL_INDEX_HOST_FPTR(LINEAR_IDX(I,J,K,IBP2,JBP2,KBP2)) + 1
            CELL_HOST_FPTR(IC * NEDGE + 2) = CELL_INDEX_HOST_FPTR(LINEAR_IDX(I+1,J,K,IBP2,JBP2,KBP2)) + 1
            CELL_HOST_FPTR(IC * NEDGE + 3) = CELL_INDEX_HOST_FPTR(LINEAR_IDX(I,J,K,IBP2,JBP2,KBP2)) + 2
            CELL_HOST_FPTR(IC * NEDGE + 4) = CELL_INDEX_HOST_FPTR(LINEAR_IDX(I,J+1,K,IBP2,JBP2,KBP2)) + 2
            CELL_HOST_FPTR(IC * NEDGE + 5) = CELL_INDEX_HOST_FPTR(LINEAR_IDX(I,J,K,IBP2,JBP2,KBP2)) + 3
            CELL_HOST_FPTR(IC * NEDGE + 6) = CELL_INDEX_HOST_FPTR(LINEAR_IDX(I,J,K-1,IBP2,JBP2,KBP2)) + 3
            CELL_HOST_FPTR(IC * NEDGE + 7) = CELL_INDEX_HOST_FPTR(LINEAR_IDX(I,J,K,IBP2,JBP2,KBP2)) + 4
            CELL_HOST_FPTR(IC * NEDGE + 8) = CELL_INDEX_HOST_FPTR(LINEAR_IDX(I,J+1,K,IBP2,JBP2,KBP2)) + 4
            CELL_HOST_FPTR(IC * NEDGE + 9) = CELL_INDEX_HOST_FPTR(LINEAR_IDX(I,J,K,IBP2,JBP2,KBP2)) + 5
            CELL_HOST_FPTR(IC * NEDGE + 10) = CELL_INDEX_HOST_FPTR(LINEAR_IDX(I,J,K-1,IBP2,JBP2,KBP2)) + 5
            CELL_HOST_FPTR(IC * NEDGE + 11) = CELL_INDEX_HOST_FPTR(LINEAR_IDX(I,J,K,IBP2,JBP2,KBP2)) + 6
            CELL_HOST_FPTR(IC * NEDGE + 12) = CELL_INDEX_HOST_FPTR(LINEAR_IDX(I+1,J,K,IBP2,JBP2,KBP2)) + 6
            DO IE=1,NEDGE
               MAX_EDGE = MAX(MAX_EDGE,CELL_HOST_FPTR(IC * NEDGE + IE))
            ENDDO
         ENDDO
      ENDDO
   ENDDO
   MAX_EDGE_P1 = MAX_EDGE + 1
   OMEGA_HOST_CPTR = OMP_TARGET_ALLOC((4*MAX_EDGE_P1+1)*REAL_BYTES,HOST_DEV)
   TAU_HOST_CPTR = OMP_TARGET_ALLOC((4*MAX_EDGE_P1+1)*REAL_BYTES,HOST_DEV)
   OMEGA_DEVICE_CPTR = OMP_TARGET_ALLOC((4*MAX_EDGE_P1+1)*REAL_BYTES,TARG_DEV)
   TAU_DEVICE_CPTR = OMP_TARGET_ALLOC((4*MAX_EDGE_P1+1)*REAL_BYTES,TARG_DEV)

   CALL C_F_POINTER(OMEGA_HOST_CPTR,OMEGA_HOST_FPTR,shape=[ 4*MAX_EDGE_P1+1 ])
   CALL C_F_POINTER(TAU_HOST_CPTR,TAU_HOST_FPTR,shape=[ 4*MAX_EDGE_P1+1 ])
   OMEGA_HOST_FPTR(:) = -1.E6_EB
   TAU_HOST_FPTR(:) = -1.E6_EB
   DO IE=1,MAX_EDGE,2
       DO I=1,4
           OMEGA_HOST_FPTR(IE * 4 + I) = 1.5E-4_EB
           TAU_HOST_FPTR(IE * 4 + I) = 2.5E-4_EB
       END DO
    ENDDO

   CALL C_F_POINTER(RHO_HOST_CPTR,RHO_HOST_FPTR,shape=[ IBP2*JBP2*KBP2 ])
   CALL C_F_POINTER(RHO_0_HOST_CPTR,RHO_0_HOST_FPTR,shape=[ KBP1 ])
   CALL C_F_POINTER(D_HOST_CPTR,D_HOST_FPTR,shape=[ IBP2*JBP2*KBP2 ])
   CALL C_F_POINTER(MU_HOST_CPTR,MU_HOST_FPTR,shape=[ IBP2*JBP2*KBP2 ])
   CALL C_F_POINTER(WORK1_HOST_CPTR,WORK1_HOST_FPTR,shape=[ IBP2*JBP2*KBP2 ])
   CALL C_F_POINTER(WORK2_HOST_CPTR,WORK2_HOST_FPTR,shape=[ IBP2*JBP2*KBP2 ])
   CALL C_F_POINTER(WORK3_HOST_CPTR,WORK3_HOST_FPTR,shape=[ IBP2*JBP2*KBP2 ])
   CALL C_F_POINTER(WORK4_HOST_CPTR,WORK4_HOST_FPTR,shape=[ IBP2*JBP2*KBP2 ])
   CALL C_F_POINTER(WORK5_HOST_CPTR,WORK5_HOST_FPTR,shape=[ IBP2*JBP2*KBP2 ])
   CALL C_F_POINTER(WORK6_HOST_CPTR,WORK6_HOST_FPTR,shape=[ IBP2*JBP2*KBP2 ])
   CALL C_F_POINTER(GX_HOST_CPTR,GX_HOST_FPTR,shape=[ IBP1 ])
   CALL C_F_POINTER(GY_HOST_CPTR,GY_HOST_FPTR,shape=[ IBP1 ])
   CALL C_F_POINTER(GZ_HOST_CPTR,GZ_HOST_FPTR,shape=[ IBP1 ])
   RHO_HOST_FPTR(:)   = 1.19_EB
   RHO_0_HOST_FPTR(:) = 1.19_EB
   D_HOST_FPTR(:)    = 0.0015_EB
   MU_HOST_FPTR(:)    = 0.0019_EB
   WORK1_HOST_FPTR(:) = 0.0_EB
   WORK2_HOST_FPTR(:) = 0.0_EB
   WORK3_HOST_FPTR(:) = 0.0_EB
   WORK4_HOST_FPTR(:) = 0.0_EB
   WORK5_HOST_FPTR(:) = 0.0_EB
   WORK6_HOST_FPTR(:) = 0.0_EB
   GX_HOST_FPTR(:) = 0.0_EB
   GY_HOST_FPTR(:) = 0.0_EB
   GZ_HOST_FPTR(:) = 1.0_EB
   
   CALL C_F_POINTER(U_HOST_CPTR,U_HOST_FPTR,shape=[ IBP2*JBP2*KBP2 ])
   CALL C_F_POINTER(V_HOST_CPTR,V_HOST_FPTR,shape=[ IBP2*JBP2*KBP2 ])
   CALL C_F_POINTER(W_HOST_CPTR,W_HOST_FPTR,shape=[ IBP2*JBP2*KBP2 ])
   ! U, V, W:
   DO K=0,KBAR
      DO J=0,JBAR
         DO I=0,IBAR
            ! Some Trig functions:
            U_HOST_FPTR(LINEAR_IDX(I,J,K,IBP2,JBP2,KBP2)) =  SIN(X_HOST_FPTR(I))*COS(Y_HOST_FPTR(J))*COS(Z_HOST_FPTR(K))
            V_HOST_FPTR(LINEAR_IDX(I,J,K,IBP2,JBP2,KBP2)) = -COS(X_HOST_FPTR(I))*SIN(Y_HOST_FPTR(J))*COS(Z_HOST_FPTR(K))
            W_HOST_FPTR(LINEAR_IDX(I,J,K,IBP2,JBP2,KBP2)) =  COS(X_HOST_FPTR(I))*COS(Y_HOST_FPTR(J))*SIN(Z_HOST_FPTR(K))
         ENDDO
      ENDDO
   ENDDO
   
   ! Compute Tau OMG:
   UU_HOST_CPTR = U_HOST_CPTR
   VV_HOST_CPTR = V_HOST_CPTR
   WW_HOST_CPTR = W_HOST_CPTR
   DP_HOST_CPTR = D_HOST_CPTR
   RHOP_HOST_CPTR = RHO_HOST_CPTR
   TXY_HOST_CPTR = WORK1_HOST_CPTR
   TXZ_HOST_CPTR = WORK2_HOST_CPTR
   TYZ_HOST_CPTR = WORK3_HOST_CPTR
   OMX_HOST_CPTR = WORK4_HOST_CPTR
   OMY_HOST_CPTR = WORK5_HOST_CPTR
   OMZ_HOST_CPTR = WORK6_HOST_CPTR
   
   CALL C_F_POINTER(UU_HOST_CPTR,UU_HOST_FPTR,shape=[ IBP2*JBP2*KBP2 ])
   CALL C_F_POINTER(VV_HOST_CPTR,VV_HOST_FPTR,shape=[ IBP2*JBP2*KBP2 ])
   CALL C_F_POINTER(WW_HOST_CPTR,WW_HOST_FPTR,shape=[ IBP2*JBP2*KBP2 ])
   CALL C_F_POINTER(DP_HOST_CPTR,DP_HOST_FPTR,shape=[ IBP2*JBP2*KBP2 ])
   CALL C_F_POINTER(RHOP_HOST_CPTR,RHOP_HOST_FPTR,shape=[ IBP2*JBP2*KBP2 ])
   CALL C_F_POINTER(MU_HOST_CPTR,MU_HOST_FPTR,shape=[ IBP2*JBP2*KBP2 ])
   CALL C_F_POINTER(OMX_HOST_CPTR,OMX_HOST_FPTR,shape=[ IBP2*JBP2*KBP2 ])
   CALL C_F_POINTER(OMY_HOST_CPTR,OMY_HOST_FPTR,shape=[ IBP2*JBP2*KBP2 ])
   CALL C_F_POINTER(OMZ_HOST_CPTR,OMZ_HOST_FPTR,shape=[ IBP2*JBP2*KBP2 ])
   CALL C_F_POINTER(TXY_HOST_CPTR,TXY_HOST_FPTR,shape=[ IBP2*JBP2*KBP2 ])
   CALL C_F_POINTER(TXZ_HOST_CPTR,TXZ_HOST_FPTR,shape=[ IBP2*JBP2*KBP2 ])
   CALL C_F_POINTER(TYZ_HOST_CPTR,TYZ_HOST_FPTR,shape=[ IBP2*JBP2*KBP2 ])
   DO K=0,KBAR
      DO J=0,JBAR
         DO I=0,IBAR
            DUDY = RDYN_HOST_FPTR(J)*(UU_HOST_FPTR(LINEAR_IDX(I,J+1,K,IBP2,JBP2,KBP2))-UU_HOST_FPTR(LINEAR_IDX(I,J,K,IBP2,JBP2,KBP2)))
            DVDX = RDXN_HOST_FPTR(I)*(VV_HOST_FPTR(LINEAR_IDX(I+1,J,K,IBP2,JBP2,KBP2))-VV_HOST_FPTR(LINEAR_IDX(I,J,K,IBP2,JBP2,KBP2)))
            DUDZ = RDZN_HOST_FPTR(K)*(UU_HOST_FPTR(LINEAR_IDX(I,J,K+1,IBP2,JBP2,KBP2))-UU_HOST_FPTR(LINEAR_IDX(I,J,K,IBP2,JBP2,KBP2)))
            DWDX = RDXN_HOST_FPTR(I)*(WW_HOST_FPTR(LINEAR_IDX(I+1,J,K,IBP2,JBP2,KBP2))-WW_HOST_FPTR(LINEAR_IDX(I,J,K,IBP2,JBP2,KBP2)))
            DVDZ = RDZN_HOST_FPTR(K)*(VV_HOST_FPTR(LINEAR_IDX(I,J,K+1,IBP2,JBP2,KBP2))-VV_HOST_FPTR(LINEAR_IDX(I,J,K,IBP2,JBP2,KBP2)))
            DWDY = RDYN_HOST_FPTR(J)*(WW_HOST_FPTR(LINEAR_IDX(I,J+1,K,IBP2,JBP2,KBP2))-WW_HOST_FPTR(LINEAR_IDX(I,J,K,IBP2,JBP2,KBP2)))
            OMX_HOST_FPTR(LINEAR_IDX(I,J,K,IBP2,JBP2,KBP2)) = DWDY - DVDZ
            OMY_HOST_FPTR(LINEAR_IDX(I,J,K,IBP2,JBP2,KBP2)) = DUDZ - DWDX
            OMZ_HOST_FPTR(LINEAR_IDX(I,J,K,IBP2,JBP2,KBP2)) = DVDX - DUDY
            MUX = 0.25_EB*(MU_HOST_FPTR(LINEAR_IDX(I,J+1,K,IBP2,JBP2,KBP2))+MU_HOST_FPTR(LINEAR_IDX(I,J,K,IBP2,JBP2,KBP2))+MU_HOST_FPTR(LINEAR_IDX(I,J,K+1,IBP2,JBP2,KBP2))+MU_HOST_FPTR(LINEAR_IDX(I,J+1,K+1,IBP2,JBP2,KBP2)))
            MUY = 0.25_EB*(MU_HOST_FPTR(LINEAR_IDX(I+1,J,K,IBP2,JBP2,KBP2))+MU_HOST_FPTR(LINEAR_IDX(I,J,K,IBP2,JBP2,KBP2))+MU_HOST_FPTR(LINEAR_IDX(I,J,K+1,IBP2,JBP2,KBP2))+MU_HOST_FPTR(LINEAR_IDX(I+1,J,K+1,IBP2,JBP2,KBP2)))
            MUZ = 0.25_EB*(MU_HOST_FPTR(LINEAR_IDX(I+1,J,K,IBP2,JBP2,KBP2))+MU_HOST_FPTR(LINEAR_IDX(I,J,K,IBP2,JBP2,KBP2))+MU_HOST_FPTR(LINEAR_IDX(I,J+1,K,IBP2,JBP2,KBP2))+MU_HOST_FPTR(LINEAR_IDX(I+1,J+1,K,IBP2,JBP2,KBP2)))
            TXY_HOST_FPTR(LINEAR_IDX(I,J,K,IBP2,JBP2,KBP2)) = MUZ*(DVDX + DUDY)
            TXZ_HOST_FPTR(LINEAR_IDX(I,J,K,IBP2,JBP2,KBP2)) = MUY*(DUDZ + DWDX)
            TYZ_HOST_FPTR(LINEAR_IDX(I,J,K,IBP2,JBP2,KBP2)) = MUX*(DVDZ + DWDY)
         ENDDO
      ENDDO
   ENDDO

   ! HD memcpys
   RC = OMP_TARGET_MEMCPY(dst=RDXN_DEVICE_CPTR,src=RDXN_HOST_CPTR,length=IBP1*REAL_BYTES, &
                          dst_offset=0_c_size_t, src_offset=0_c_size_t, &
                          dst_device_num=TARG_DEV,src_device_num=HOST_DEV)
   RC = OMP_TARGET_MEMCPY(dst=RDYN_DEVICE_CPTR,src=RDYN_HOST_CPTR,length=JBP1*REAL_BYTES, &
                          dst_offset=0_c_size_t, src_offset=0_c_size_t, &
                          dst_device_num=TARG_DEV,src_device_num=HOST_DEV)
   RC = OMP_TARGET_MEMCPY(dst=RDZN_DEVICE_CPTR,src=RDZN_HOST_CPTR,length=KBP1*REAL_BYTES, &
                          dst_offset=0_c_size_t, src_offset=0_c_size_t, &
                          dst_device_num=TARG_DEV,src_device_num=HOST_DEV)
   RC = OMP_TARGET_MEMCPY(dst=RDX_DEVICE_CPTR,src=RDX_HOST_CPTR,length=IBP1*REAL_BYTES, &
                          dst_offset=0_c_size_t, src_offset=0_c_size_t, &
                          dst_device_num=TARG_DEV,src_device_num=HOST_DEV)
   RC = OMP_TARGET_MEMCPY(dst=RDY_DEVICE_CPTR,src=RDY_HOST_CPTR,length=JBP1*REAL_BYTES, &
                          dst_offset=0_c_size_t, src_offset=0_c_size_t, &
                          dst_device_num=TARG_DEV,src_device_num=HOST_DEV)
   RC = OMP_TARGET_MEMCPY(dst=RDZ_DEVICE_CPTR,src=RDZ_HOST_CPTR,length=KBP1*REAL_BYTES, &
                          dst_offset=0_c_size_t, src_offset=0_c_size_t, &
                          dst_device_num=TARG_DEV,src_device_num=HOST_DEV)
   RC = OMP_TARGET_MEMCPY(dst=CELL_INDEX_DEVICE_CPTR,src=CELL_INDEX_HOST_CPTR,length=IBP2*JBP2*KBP2*INT_BYTES, &
                          dst_offset=0_c_size_t, src_offset=0_c_size_t, &
                          dst_device_num=TARG_DEV,src_device_num=HOST_DEV)
   RC = OMP_TARGET_MEMCPY(dst=RHO_DEVICE_CPTR,src=RHO_HOST_CPTR,length=IBP2*JBP2*KBP2*REAL_BYTES, &
                          dst_offset=0_c_size_t, src_offset=0_c_size_t, &
                          dst_device_num=TARG_DEV,src_device_num=HOST_DEV)
   RC = OMP_TARGET_MEMCPY(dst=D_DEVICE_CPTR,src=D_HOST_CPTR,length=IBP2*JBP2*KBP2*REAL_BYTES, &
                          dst_offset=0_c_size_t, src_offset=0_c_size_t, &
                          dst_device_num=TARG_DEV,src_device_num=HOST_DEV)
   RC = OMP_TARGET_MEMCPY(dst=MU_DEVICE_CPTR,src=MU_HOST_CPTR,length=IBP2*JBP2*KBP2*REAL_BYTES, &
                          dst_offset=0_c_size_t, src_offset=0_c_size_t, &
                          dst_device_num=TARG_DEV,src_device_num=HOST_DEV)
   RC = OMP_TARGET_MEMCPY(dst=WORK1_DEVICE_CPTR,src=WORK1_HOST_CPTR,length=IBP2*JBP2*KBP2*REAL_BYTES, &
                          dst_offset=0_c_size_t, src_offset=0_c_size_t, &
                          dst_device_num=TARG_DEV,src_device_num=HOST_DEV)
   RC = OMP_TARGET_MEMCPY(dst=WORK2_DEVICE_CPTR,src=WORK2_HOST_CPTR,length=IBP2*JBP2*KBP2*REAL_BYTES, &
                          dst_offset=0_c_size_t, src_offset=0_c_size_t, &
                          dst_device_num=TARG_DEV,src_device_num=HOST_DEV)
   RC = OMP_TARGET_MEMCPY(dst=WORK3_DEVICE_CPTR,src=WORK3_HOST_CPTR,length=IBP2*JBP2*KBP2*REAL_BYTES, &
                          dst_offset=0_c_size_t, src_offset=0_c_size_t, &
                          dst_device_num=TARG_DEV,src_device_num=HOST_DEV)
   RC = OMP_TARGET_MEMCPY(dst=WORK4_DEVICE_CPTR,src=WORK4_HOST_CPTR,length=IBP2*JBP2*KBP2*REAL_BYTES, &
                          dst_offset=0_c_size_t, src_offset=0_c_size_t, &
                          dst_device_num=TARG_DEV,src_device_num=HOST_DEV)
   RC = OMP_TARGET_MEMCPY(dst=WORK5_DEVICE_CPTR,src=WORK5_HOST_CPTR,length=IBP2*JBP2*KBP2*REAL_BYTES, &
                          dst_offset=0_c_size_t, src_offset=0_c_size_t, &
                          dst_device_num=TARG_DEV,src_device_num=HOST_DEV)
   RC = OMP_TARGET_MEMCPY(dst=WORK6_DEVICE_CPTR,src=WORK6_HOST_CPTR,length=IBP2*JBP2*KBP2*REAL_BYTES, &
                          dst_offset=0_c_size_t, src_offset=0_c_size_t, &
                          dst_device_num=TARG_DEV,src_device_num=HOST_DEV)
   RC = OMP_TARGET_MEMCPY(dst=RHO_0_DEVICE_CPTR,src=RHO_0_HOST_CPTR,length=KBP1*REAL_BYTES, &
                          dst_offset=0_c_size_t, src_offset=0_c_size_t, &
                          dst_device_num=TARG_DEV,src_device_num=HOST_DEV)
   RC = OMP_TARGET_MEMCPY(dst=GX_DEVICE_CPTR,src=GX_HOST_CPTR,length=IBP1*REAL_BYTES, &
                          dst_offset=0_c_size_t, src_offset=0_c_size_t, &
                          dst_device_num=TARG_DEV,src_device_num=HOST_DEV)
   RC = OMP_TARGET_MEMCPY(dst=GY_DEVICE_CPTR,src=GY_HOST_CPTR,length=IBP1*REAL_BYTES, &
                          dst_offset=0_c_size_t, src_offset=0_c_size_t, &
                          dst_device_num=TARG_DEV,src_device_num=HOST_DEV)
   RC = OMP_TARGET_MEMCPY(dst=GZ_DEVICE_CPTR,src=GZ_HOST_CPTR,length=IBP1*REAL_BYTES, &
                          dst_offset=0_c_size_t, src_offset=0_c_size_t, &
                          dst_device_num=TARG_DEV,src_device_num=HOST_DEV)
   RC = OMP_TARGET_MEMCPY(dst=U_DEVICE_CPTR,src=U_HOST_CPTR,length=IBP2*JBP2*KBP2*REAL_BYTES, &
                          dst_offset=0_c_size_t, src_offset=0_c_size_t, &
                          dst_device_num=TARG_DEV,src_device_num=HOST_DEV)
   RC = OMP_TARGET_MEMCPY(dst=V_DEVICE_CPTR,src=V_HOST_CPTR,length=IBP2*JBP2*KBP2*REAL_BYTES, &
                          dst_offset=0_c_size_t, src_offset=0_c_size_t, &
                          dst_device_num=TARG_DEV,src_device_num=HOST_DEV)
   RC = OMP_TARGET_MEMCPY(dst=W_DEVICE_CPTR,src=W_HOST_CPTR,length=IBP2*JBP2*KBP2*REAL_BYTES, &
                          dst_offset=0_c_size_t, src_offset=0_c_size_t, &
                          dst_device_num=TARG_DEV,src_device_num=HOST_DEV)
   RC = OMP_TARGET_MEMCPY(dst=FVX_DEVICE_CPTR,src=FVX_HOST_CPTR,length=IBP2*JBP2*KBP2*REAL_BYTES, &
                          dst_offset=0_c_size_t, src_offset=0_c_size_t, &
                          dst_device_num=TARG_DEV,src_device_num=HOST_DEV)
   RC = OMP_TARGET_MEMCPY(dst=FVY_DEVICE_CPTR,src=FVY_HOST_CPTR,length=IBP2*JBP2*KBP2*REAL_BYTES, &
                          dst_offset=0_c_size_t, src_offset=0_c_size_t, &
                          dst_device_num=TARG_DEV,src_device_num=HOST_DEV)
   RC = OMP_TARGET_MEMCPY(dst=FVZ_DEVICE_CPTR,src=FVZ_HOST_CPTR,length=IBP2*JBP2*KBP2*REAL_BYTES, &
                          dst_offset=0_c_size_t, src_offset=0_c_size_t, &
                          dst_device_num=TARG_DEV,src_device_num=HOST_DEV)
   RC = OMP_TARGET_MEMCPY(dst=CELL_DEVICE_CPTR,src=CELL_HOST_CPTR,length=(NEDGE*ICMAX+1)*INT_BYTES, &
                          dst_offset=0_c_size_t, src_offset=0_c_size_t, &
                          dst_device_num=TARG_DEV,src_device_num=HOST_DEV)
   RC = OMP_TARGET_MEMCPY(dst=OMEGA_DEVICE_CPTR,src=OMEGA_HOST_CPTR,length=(4*MAX_EDGE_P1+1)*REAL_BYTES, &
                          dst_offset=0_c_size_t, src_offset=0_c_size_t, &
                          dst_device_num=TARG_DEV,src_device_num=HOST_DEV)
   RC = OMP_TARGET_MEMCPY(dst=TAU_DEVICE_CPTR,src=TAU_HOST_CPTR,length=(4*MAX_EDGE_P1+1)*REAL_BYTES, &
                          dst_offset=0_c_size_t, src_offset=0_c_size_t, &
                          dst_device_num=TARG_DEV,src_device_num=HOST_DEV)
   UU_DEVICE_CPTR = U_DEVICE_CPTR
   VV_DEVICE_CPTR = V_DEVICE_CPTR
   WW_DEVICE_CPTR = W_DEVICE_CPTR
   DP_DEVICE_CPTR = D_DEVICE_CPTR
   RHOP_DEVICE_CPTR = RHO_DEVICE_CPTR
   TXY_DEVICE_CPTR = WORK1_DEVICE_CPTR
   TXZ_DEVICE_CPTR = WORK2_DEVICE_CPTR
   TYZ_DEVICE_CPTR = WORK3_DEVICE_CPTR
   OMX_DEVICE_CPTR = WORK4_DEVICE_CPTR
   OMY_DEVICE_CPTR = WORK5_DEVICE_CPTR
   OMZ_DEVICE_CPTR = WORK6_DEVICE_CPTR

   T_NOW = OMP_GET_WTIME()
   SIM_LOOP: DO ISTEP = 1, NUM_TIME_STEPS
      CALL LOOP3D_OMP_GPU()
   END DO SIM_LOOP
   T_END = OMP_GET_WTIME()
   
   RC = OMP_TARGET_MEMCPY(dst=FVX_HOST_CPTR,src=FVX_DEVICE_CPTR,length=IBP2*JBP2*KBP2*REAL_BYTES, &
                          dst_offset=0_c_size_t, src_offset=0_c_size_t, &
                          dst_device_num=HOST_DEV,src_device_num=TARG_DEV)

   CALL C_F_POINTER(FVX_HOST_CPTR,FVX_HOST_FPTR,shape=[ IBP2*JBP2*KBP2 ])

   FVX_AVG = 0
   FVY_AVG = 0
   FVZ_AVG = 0
   DO I=1,IBAR
      DO J=1,JBAR
         DO K=1,KBAR
            FVX_AVG = FVX_AVG + FVX_HOST_FPTR(LINEAR_IDX(I,J,K,IBP2,JBP2,KBP2))
         END DO
      END DO
   END DO
   FVX_AVG = FVX_AVG / (IBAR * JBAR * KBAR)

   WRITE(10,*) 'Time=',T_END-T_NOW
   WRITE(10,*) 'mean FVX =',FVX_AVG
   WRITE(10,*) 'Ending Loop3D'
   CLOSE(10)
   WRITE(*,*) 'Loop3D done.'
   
   CONTAINS
   
   SUBROUTINE LOOP3D_OMP_GPU()
      
      ! Compute x-direction flux term FVX
      !$OMP TARGET DATA &
      !$OMP USE_DEVICE_PTR(RDXN_DEVICE_CPTR,RDYN_DEVICE_CPTR,RDZN_DEVICE_CPTR) &
      !$OMP USE_DEVICE_PTR(RDX_DEVICE_CPTR,RDY_DEVICE_CPTR,RDZ_DEVICE_CPTR) &
      !$OMP USE_DEVICE_PTR(CELL_INDEX_DEVICE_CPTR,RHOP_DEVICE_CPTR,DP_DEVICE_CPTR) &
      !$OMP USE_DEVICE_PTR(MU_DEVICE_CPTR,TXY_DEVICE_CPTR,TXZ_DEVICE_CPTR) &
      !$OMP USE_DEVICE_PTR(TYZ_DEVICE_CPTR,OMX_DEVICE_CPTR,OMY_DEVICE_CPTR) &
      !$OMP USE_DEVICE_PTR(OMZ_DEVICE_CPTR,RHO_0_DEVICE_CPTR,GX_DEVICE_CPTR) &
      !$OMP USE_DEVICE_PTR(GY_DEVICE_CPTR,GZ_DEVICE_CPTR,FVX_DEVICE_CPTR) &
      !$OMP USE_DEVICE_PTR(UU_DEVICE_CPTR,VV_DEVICE_CPTR,WW_DEVICE_CPTR) &
      !$OMP USE_DEVICE_PTR(FVY_DEVICE_CPTR,FVZ_DEVICE_CPTR,CELL_DEVICE_CPTR) &
      !$OMP USE_DEVICE_PTR(OMEGA_DEVICE_CPTR,TAU_DEVICE_CPTR)

      CALL C_F_POINTER(RDXN_DEVICE_CPTR,RDXN_DEVICE_FPTR,shape=[ IBP1 ])
      CALL C_F_POINTER(RDYN_DEVICE_CPTR,RDYN_DEVICE_FPTR,shape=[ JBP1 ])
      CALL C_F_POINTER(RDZN_DEVICE_CPTR,RDZN_DEVICE_FPTR,shape=[ KBP1 ])
      CALL C_F_POINTER(RDX_DEVICE_CPTR,RDX_DEVICE_FPTR,shape=[ IBP1 ])
      CALL C_F_POINTER(RDY_DEVICE_CPTR,RDY_DEVICE_FPTR,shape=[ JBP1 ])
      CALL C_F_POINTER(RDZ_DEVICE_CPTR,RDZ_DEVICE_FPTR,shape=[ KBP1 ])
      CALL C_F_POINTER(CELL_INDEX_DEVICE_CPTR,CELL_INDEX_DEVICE_FPTR,shape=[ IBP2*JBP2*KBP2 ])
      CALL C_F_POINTER(RHOP_DEVICE_CPTR,RHOP_DEVICE_FPTR,shape=[ IBP2*JBP2*KBP2 ])
      CALL C_F_POINTER(DP_DEVICE_CPTR,DP_DEVICE_FPTR,shape=[ IBP2*JBP2*KBP2 ])
      CALL C_F_POINTER(MU_DEVICE_CPTR,MU_DEVICE_FPTR,shape=[ IBP2*JBP2*KBP2 ])
      CALL C_F_POINTER(TXY_DEVICE_CPTR,TXY_DEVICE_FPTR,shape=[ IBP2*JBP2*KBP2 ])
      CALL C_F_POINTER(TXZ_DEVICE_CPTR,TXZ_DEVICE_FPTR,shape=[ IBP2*JBP2*KBP2 ])
      CALL C_F_POINTER(TYZ_DEVICE_CPTR,TYZ_DEVICE_FPTR,shape=[ IBP2*JBP2*KBP2 ])
      CALL C_F_POINTER(OMX_DEVICE_CPTR,OMX_DEVICE_FPTR,shape=[ IBP2*JBP2*KBP2 ])
      CALL C_F_POINTER(OMY_DEVICE_CPTR,OMY_DEVICE_FPTR,shape=[ IBP2*JBP2*KBP2 ])
      CALL C_F_POINTER(OMZ_DEVICE_CPTR,OMZ_DEVICE_FPTR,shape=[ IBP2*JBP2*KBP2 ])
      CALL C_F_POINTER(RHO_0_DEVICE_CPTR,RHO_0_DEVICE_FPTR,shape=[ KBP1 ])
      CALL C_F_POINTER(GX_DEVICE_CPTR,GX_DEVICE_FPTR,shape=[ IBP1 ])
      CALL C_F_POINTER(GY_DEVICE_CPTR,GY_DEVICE_FPTR,shape=[ IBP1 ])
      CALL C_F_POINTER(GZ_DEVICE_CPTR,GZ_DEVICE_FPTR,shape=[ IBP1 ])
      CALL C_F_POINTER(UU_DEVICE_CPTR,UU_DEVICE_FPTR,shape=[ IBP2*JBP2*KBP2 ])
      CALL C_F_POINTER(VV_DEVICE_CPTR,VV_DEVICE_FPTR,shape=[ IBP2*JBP2*KBP2 ])
      CALL C_F_POINTER(WW_DEVICE_CPTR,WW_DEVICE_FPTR,shape=[ IBP2*JBP2*KBP2 ])
      CALL C_F_POINTER(FVX_DEVICE_CPTR,FVX_DEVICE_FPTR,shape=[ IBP2*JBP2*KBP2 ])
      CALL C_F_POINTER(FVY_DEVICE_CPTR,FVY_DEVICE_FPTR,shape=[ IBP2*JBP2*KBP2 ])
      CALL C_F_POINTER(FVZ_DEVICE_CPTR,FVZ_DEVICE_FPTR,shape=[ IBP2*JBP2*KBP2 ])
      CALL C_F_POINTER(CELL_DEVICE_CPTR,CELL_DEVICE_FPTR,shape=[ NEDGE*ICMAX+1 ])
      CALL C_F_POINTER(OMEGA_DEVICE_CPTR,OMEGA_DEVICE_FPTR,shape=[ 4*MAX_EDGE_P1+1 ])
      CALL C_F_POINTER(TAU_DEVICE_CPTR,TAU_DEVICE_FPTR,shape=[ 4*MAX_EDGE_P1+1 ])

      !$OMP TARGET TEAMS DISTRIBUTE PARALLEL DO NUM_THREADS(128) COLLAPSE(3)
       DO K=1,KBAR
        DO J=1,JBAR
           DO I=0,IBAR
              WP    = WW_DEVICE_FPTR(LINEAR_IDX(I,J,K,IBP2,JBP2,KBP2))   + WW_DEVICE_FPTR(LINEAR_IDX(I+1,J,K,IBP2,JBP2,KBP2))
              WM    = WW_DEVICE_FPTR(LINEAR_IDX(I,J,K-1,IBP2,JBP2,KBP2)) + WW_DEVICE_FPTR(LINEAR_IDX(I+1,J,K-1,IBP2,JBP2,KBP2))
              VP    = VV_DEVICE_FPTR(LINEAR_IDX(I,J,K,IBP2,JBP2,KBP2))   + VV_DEVICE_FPTR(LINEAR_IDX(I+1,J,K,IBP2,JBP2,KBP2))
              VM    = VV_DEVICE_FPTR(LINEAR_IDX(I,J-1,K,IBP2,JBP2,KBP2)) + VV_DEVICE_FPTR(LINEAR_IDX(I+1,J-1,K,IBP2,JBP2,KBP2))
              OMYP  = OMY_DEVICE_FPTR(LINEAR_IDX(I,J,K,IBP2,JBP2,KBP2))
              OMYM  = OMY_DEVICE_FPTR(LINEAR_IDX(I,J,K-1,IBP2,JBP2,KBP2))
              OMZP  = OMZ_DEVICE_FPTR(LINEAR_IDX(I,J,K,IBP2,JBP2,KBP2))
              OMZM  = OMZ_DEVICE_FPTR(LINEAR_IDX(I,J-1,K,IBP2,JBP2,KBP2))
              TXZP  = TXZ_DEVICE_FPTR(LINEAR_IDX(I,J,K,IBP2,JBP2,KBP2))
              TXZM  = TXZ_DEVICE_FPTR(LINEAR_IDX(I,J,K-1,IBP2,JBP2,KBP2))
              TXYP  = TXY_DEVICE_FPTR(LINEAR_IDX(I,J,K,IBP2,JBP2,KBP2))
              TXYM  = TXY_DEVICE_FPTR(LINEAR_IDX(I,J-1,K,IBP2,JBP2,KBP2))
              IC    = CELL_INDEX_DEVICE_FPTR(LINEAR_IDX(I,J,K,IBP2,JBP2,KBP2))
              IEYP = CELL_DEVICE_FPTR(IC * NEDGE + 8)
              IEYM = CELL_DEVICE_FPTR(IC * NEDGE + 6)
              IEZP = CELL_DEVICE_FPTR(IC * NEDGE + 12)
              IEZM = CELL_DEVICE_FPTR(IC * NEDGE + 10)
              IF (OMEGA_DEVICE_FPTR(IEYP * 4 + 1)>-1.E5) THEN
                  OMYP = OMEGA_DEVICE_FPTR(IEYP * 4 + 1)
                  TXZP = TAU_DEVICE_FPTR(IEYP * 4 + 1)
               ENDIF
               IF (OMEGA_DEVICE_FPTR(IEYM * 4 + 2)>-1.E5) THEN
                  OMYM = OMEGA_DEVICE_FPTR(IEYM * 4 + 2)
                  TXZM = TAU_DEVICE_FPTR(IEYM * 4 + 2)
               ENDIF
               IF (OMEGA_DEVICE_FPTR(IEZP * 4 + 3)>-1.E5) THEN
                  OMZP = OMEGA_DEVICE_FPTR(IEZP * 4 + 3)
                  TXYP = TAU_DEVICE_FPTR(IEZP * 4 + 3)
               ENDIF
               IF (OMEGA_DEVICE_FPTR(IEZM * 4 + 4)>-1.E5) THEN
                  OMZM = OMEGA_DEVICE_FPTR(IEZM * 4 + 4)
                  TXYM = TAU_DEVICE_FPTR(IEZM * 4 + 4)
               ENDIF
              WOMY  = WP*OMYP + WM*OMYM
              VOMZ  = VP*OMZP + VM*OMZM
              RRHO  = 2._EB/(RHOP_DEVICE_FPTR(LINEAR_IDX(I,J,K,IBP2,JBP2,KBP2))+RHOP_DEVICE_FPTR(LINEAR_IDX(I+1,J,K,IBP2,JBP2,KBP2)))
              DVDY  = (VV_DEVICE_FPTR(LINEAR_IDX(I+1,J,K,IBP2,JBP2,KBP2))-VV_DEVICE_FPTR(LINEAR_IDX(I+1,J-1,K,IBP2,JBP2,KBP2)))*RDY_DEVICE_FPTR(J)
              DWDZ  = (WW_DEVICE_FPTR(LINEAR_IDX(I+1,J,K,IBP2,JBP2,KBP2))-WW_DEVICE_FPTR(LINEAR_IDX(I+1,J,K-1,IBP2,JBP2,KBP2)))*RDZ_DEVICE_FPTR(K)
              TXXP  = MU_DEVICE_FPTR(LINEAR_IDX(I+1,J,K,IBP2,JBP2,KBP2))*( FOTH*DP_DEVICE_FPTR(LINEAR_IDX(I+1,J,K,IBP2,JBP2,KBP2)) - 2._EB*(DVDY+DWDZ) )
              DVDY  = (VV_DEVICE_FPTR(LINEAR_IDX(I,J,K,IBP2,JBP2,KBP2))-VV_DEVICE_FPTR(LINEAR_IDX(I,J-1,K,IBP2,JBP2,KBP2)))*RDY_DEVICE_FPTR(J)
              DWDZ  = (WW_DEVICE_FPTR(LINEAR_IDX(I,J,K,IBP2,JBP2,KBP2))-WW_DEVICE_FPTR(LINEAR_IDX(I,J,K-1,IBP2,JBP2,KBP2)))*RDZ_DEVICE_FPTR(K)
              TXXM  = MU_DEVICE_FPTR(LINEAR_IDX(I,J,K,IBP2,JBP2,KBP2))  *( FOTH*DP_DEVICE_FPTR(LINEAR_IDX(I,J,K,IBP2,JBP2,KBP2))   - 2._EB*(DVDY+DWDZ) )
              DTXXDX= RDXN_DEVICE_FPTR(I)*(TXXP-TXXM)
              DTXYDY= RDY_DEVICE_FPTR(J) *(TXYP-TXYM)
              DTXZDZ= RDZ_DEVICE_FPTR(K) *(TXZP-TXZM)
              VTRM  = DTXXDX + DTXYDY + DTXZDZ
              FVX_DEVICE_FPTR(LINEAR_IDX(I,J,K,IBP2,JBP2,KBP2)) = 0.25_EB*(WOMY - VOMZ) - GX_DEVICE_FPTR(I) + RRHO*(GX_DEVICE_FPTR(I)*RHO_0_DEVICE_FPTR(K) - VTRM)
           ENDDO
        ENDDO
     ENDDO
     !$OMP END TARGET DATA
   END SUBROUTINE LOOP3D_OMP_GPU

   INTEGER FUNCTION LINEAR_IDX(I,J,K,I_LEN,J_LEN,K_LEN)
    INTEGER, INTENT(IN) :: I, J, K, I_LEN, J_LEN, K_LEN
    LINEAR_IDX = I + I_LEN * J + I_LEN * J_LEN * K
   END FUNCTION LINEAR_IDX
   
   END PROGRAM LOOP3D
   
   
   
   
   
